# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 511cafa9f5200e622d4a6f6e57bfae4c0dc7b2b86fdb86ff83b7f4062d774d528969e788664ef55f222b1f790d50eb4daf20c56a9b2a5f3fa8919fde794f81ec

test:
  secret_key_base: a0b6de39b1ded863fa21a99249f94f917b0cfb374d10cecf5bb06025be7c1a9f5fdf0e99332a010575f8b8d28aa12e6bb68e8819d350ef9d2811044eca704860

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
